version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile.backend
    volumes:
      - .:/workspace
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - mongodb
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
      - MONGODB_URI=mongodb://mongodb:27017

  frontend:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile.frontend
    volumes:
      - .:/workspace
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3000

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  postgres_data:
  mongodb_data: 