FROM node:22-bookworm

# pnpmのインストール
RUN npm install -g pnpm

# 作業ディレクトリの設定
WORKDIR /workspaces/frontend

# 必要なファイルをコピー
COPY frontend/package.json frontend/pnpm-lock.yaml* ./

# 依存関係のインストール
RUN pnpm install

# 残りのファイルをコピー
COPY frontend/ .

# コンテナ起動時のコマンド
CMD ["pnpm", "dev"] 