FROM rust:1-bookworm AS dev

WORKDIR /workspaces

COPY .dockerignore ./

COPY backend/ ./backend/
COPY Cargo.toml ./
COPY Cargo.lock ./

RUN rustup default stable \
    && rustup component add rustfmt clippy \
    && cargo install cargo-watch
