FROM rust:1-bookworm AS dev

WORKDIR /workspaces

COPY .. .

RUN rustup default stable \
    && rustup component add rustfmt clippy \
    && cargo install cargo-watch \
    && mkdir -p target
