services:
  backend:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    container_name: boardcraft-backend
    volumes:
      - ..:/workspaces/boardcraft
    working_dir: /workspaces/boardcraft
    # user: vscode
    command: sleep infinity

  postgres:
    image: postgres:15
    container_name: boardcraft-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  surrealdb:
    image: surrealdb/surrealdb:latest
    container_name: boardcraft-surrealdb
    volumes:
      - surrealdb_data:/data
    command: ["start", "--user", "root", "--pass", "root", "--auth", "--bind", "0.0.0.0:8000", "file:///data/database.db"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  surrealdb_data:
  cargo-cache: